plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cometinhastudios.wudroid.tvcast'
    compileSdk 35

    defaultConfig {
        applicationId 'com.cometinhastudios.wudroid.tvcast'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '0.1.2TV-cast-test2-universal'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
